### ISSUE TITLE
Windows error on this line, which results in showing full path in bufferlist

### ISSUE THREAD

**Issue by IRooc** [mong8se/buffish.nvim#1]
Hi it seems to basically work fine on windows, only that it always shows full paths on windows. (Which for me is fine btw)

it is probably caused by a startup error on this line:
https://github.com/mong8se/buffish.nvim/blob/b9701bc7dd912cf1b5633043168192d1e2bd35b4/plugin/buffish.vim#LL20C88-L20C88

```
Error detected while processing C:\Users\username\AppData\Local\nvim-data\site\pack\packer\start\buffish.nvim\plugin\buffish.vim:
line   20:
E5107: Error loading lua [string ":lua"]:1: invalid escape sequence near '';C:'
```

Still using it and it is small and clean enough for my purposes.

**Comment by mong8se** [comment]
Oh hi, thanks for reaching out. I had no idea anyone but me was using this. I'll take a look at your PR

**Comment by IRooc** [comment]
I like it for it's simplicity. And the MRU ordering is great. 

Feel free to ignore or merge partly only. Main windows thing was the path \ vs /

Thanks for the work
Roderic

**Comment by mong8se** [comment]
Thanks for fixing it for windows! I've merged your PR, but I did revert the numbering back to the buffer number rather than the line number.

**Comment by IRooc** [comment]
Cool thanks, the buffer number turned out to be more than 100 on windows sometimes, and then that line failed. that's why I changed it

**Comment by mong8se** [comment]
I see! I just pushed a fix which moves the buffer number from the signs column to virtual text. Still needs some look and feel massaging but at least it's not broken with numbers greater than 2 digits.

Also fixes a couple other bugs.
